version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/ultrabox/hostfiles/data/certbot/conf:/etc/letsencrypt
      - /home/ultrabox/hostfiles/data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    command: /bin/sh -c "nginx -g 'daemon off;'"
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - /home/ultrabox/hostfiles/data/certbot/conf:/etc/letsencrypt
      - /home/ultrabox/hostfiles/data/certbot/www:/var/www/certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"